### ISSUE TITLE
can't logout remotely

### ISSUE THREAD

**Issue by ghost** [PRayno/CasAuthBundle#13]
I've noticed that the parameter "server_logout_url" is not used anywhere, so when I logout, I do just localy, when I try to login the 2nd time, I happens automatically because I'm always connected on sso server.

**Comment by micayael** [comment]
+1

**Comment by micayael** [comment]
Hi. Is there some fix for this?

**Comment by junowilderness** [comment]
@micayael 

You can make a [logout success handler](https://symfony.com/doc/current/security.html#logging-out) that redirects. This works perfectly:

security.yml:

```
# ...
    firewalls:
        secure:
           # ...
            guard:
                authenticators:
                    - prayno.cas_authenticator
            logout:
                path: /logout
                success_handler: AppBundle\Component\User\Cas\LogoutSuccessHandler
```

```
<?php

namespace AppBundle\Component\User\Cas;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Http\Logout\LogoutSuccessHandlerInterface;

class LogoutSuccessHandler implements LogoutSuccessHandlerInterface
{
    private $logoutUrl;

    public function __construct(string $logoutUrl)
    {
        $this->logoutUrl = $logoutUrl;
    }

    public function onLogoutSuccess(Request $request)
    {
        return new RedirectResponse($this->logoutUrl);
    }
}
```

Of course you must provide the URL to the class.

services.yml:

```
    AppBundle\Component\User\Cas\LogoutSuccessHandler:
        arguments:
            $logoutUrl: "%cas_logout_url%"
```

Alternatively,  you can specify a logout target path that is _outside the CAS security firewall_ that redirects to the CAS logout URL.
