### ISSUE TITLE
How to pass options to the Guzzle Client?

### ISSUE THREAD

**Issue by mdevlamynck** [PRayno/CasAuthBundle#31]
I fail to understand how to use the `options` configuration of this bundle. The `Configuration` defines it as an array of scalars and (if I'm not mistaken) the Guzzle Client expects an associative array of the form `['config key' => 'value']`.

So it seems I need to use it like so :
```yaml
p_rayno_cas_auth:
    …
    options:
        some_option_1: "some_value_1"
        some_option_2: "some_value_2"
```
When the bundle's config only accepts
```yaml
p_rayno_cas_auth:
    …
    options:
        - "some_scalar_1"
        - "some_scalar_2"
```
Am I missing something?
